### ISSUE TITLE
Fails to add new user in 10.11.6

### ISSUE THREAD

**Issue by aysiu** [square/fde-rekey#4]
I have a user on El Capitan, and when I try to run fde-rekey, the .pkg. I get this cryptic error:
```
installer: Package name is 
installer: Upgrading at base path /
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
```
When I manually download `fdeadduser` and then ran the postinstall script, I got this:
```
2017-11-08 08:45:30.308 sysadminctl[91150:11667284] Creating user record…
2017-11-08 08:45:32.125 sysadminctl[91150:11667284] Assigning UID: 2
2017-11-08 08:45:33.047 sysadminctl[91150:11667284] Creating home directory at /Users/fderekey
Found User "fderekey" in user list.
Traceback (most recent call last):
  File "fderekey.py", line 314, in <module>
    main()
  File "fderekey.py", line 290, in main
    if not add_fv_user(fdeadduser, fv_user, fv_password):
  File "fderekey.py", line 151, in add_fv_user
    subprocess.call(add_user_cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```
Any ideas? This isn't on AD, so no password requirements.

**Comment by aysiu** [comment]
Okay. Ran it again, and got this weird bit in the beginning.
```
2017-11-08 09:02:15.112 sysadminctl[93077:11680865] Creating user record…
2017-11-08 09:02:15.132 sysadminctl[93077:11680865] ### Error:-14135 File:/Library/Caches/com.apple.xbs/Sources/Admin/Admin-633/DSRecord.m Line:501
2017-11-08 09:02:15.133 sysadminctl[93077:11680865] Assigning UID: 2
2017-11-08 09:02:16.143 sysadminctl[93077:11680865] Creating home directory at /Users/fderekey
```

**Comment by weswhet** [comment]
That looks fine. Can you provide the part of the log for the install from `/var/log/install.log` after running the pkg.

**Comment by aysiu** [comment]
Okay, @weswhet. Finally got back to the machine. This is what's in the /var/log/install.log:
```
Nov  8 08:54:15 NAMEOFMACHINE installer[92957]: Product archive /Library/Managed Installs/Cache/fde-rekey-1.0.2.pkg trustLevel=100
Nov  8 08:54:15 NAMEOFMACHINE installer[92957]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Nov  8 08:54:15 NAMEOFMACHINE installer[92957]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Library/Managed%20Installs/Cache/fde-rekey-1.0.2.pkg#fde-rekey.pkg
Nov  8 08:54:15 NAMEOFMACHINE installer[92957]: Set authorization level to root for session
Nov  8 08:54:15 NAMEOFMACHINE installer[92957]: Administrator authorization granted.
Nov  8 08:54:15 NAMEOFMACHINE installer[92957]: Will use PK session
Nov  8 08:54:15 NAMEOFMACHINE installer[92957]: Using authorization level of root for IFPKInstallElement
Nov  8 08:54:15 NAMEOFMACHINE installer[92957]: Starting installation:
Nov  8 08:54:15 NAMEOFMACHINE installer[92957]: Configuring volume "Macintosh HD"
Nov  8 08:54:15 NAMEOFMACHINE installer[92957]: Preparing disk for local booted install.
Nov  8 08:54:15 NAMEOFMACHINE installer[92957]: Free space on "Macintosh HD": 48.87 GB (48874749952 bytes).
Nov  8 08:54:15 NAMEOFMACHINE installer[92957]: Create temporary directory "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T//Install.92957x6RhxK"
Nov  8 08:54:15 NAMEOFMACHINE installer[92957]: IFPKInstallElement (1 packages)
Nov  8 08:54:15 NAMEOFMACHINE installd[79389]: PackageKit: Adding client PKInstallDaemonClient pid=92957, uid=0 (/usr/sbin/installer)
Nov  8 08:54:15 NAMEOFMACHINE installer[92957]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Nov  8 08:54:15 NAMEOFMACHINE installd[79389]: PackageKit: ----- Begin install -----
Nov  8 08:54:15 NAMEOFMACHINE installd[79389]: PackageKit: request=PKInstallRequest <1 packages, destination=/>
Nov  8 08:54:15 NAMEOFMACHINE installd[79389]: PackageKit: packages=(
	    "PKLeopardPackage <file://localhost/Library/Managed%20Installs/Cache/fde-rekey-1.0.2.pkg#fde-rekey.pkg>"
	)
Nov  8 08:54:15 NAMEOFMACHINE installd[79389]: PackageKit: Will do receipt-based obsoleting for package identifier com.github.square.fderekey (prefix path=)
Nov  8 08:54:15 NAMEOFMACHINE installd[79389]: PackageKit: Extracting file://localhost/Library/Managed%20Installs/Cache/fde-rekey-1.0.2.pkg#fde-rekey.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/7F9A5C77-AE68-476B-8B3D-C67D8F0E61B6.activeSandbox/Root, uid=0)
Nov  8 08:54:15 NAMEOFMACHINE installd[79389]: PackageKit: prevent user idle system sleep
Nov  8 08:54:15 NAMEOFMACHINE installd[79389]: PackageKit: suspending backupd
Nov  8 08:54:15 NAMEOFMACHINE installd[79389]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/7F9A5C77-AE68-476B-8B3D-C67D8F0E61B6.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/7F9A5C77-AE68-476B-8B3D-C67D8F0E61B6.activeSandbox
Nov  8 08:54:15 NAMEOFMACHINE installd[79389]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/7F9A5C77-AE68-476B-8B3D-C67D8F0E61B6.activeSandbox/Root (1 items) to /
Nov  8 08:54:15 NAMEOFMACHINE installd[79389]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.L4dZBp/Scripts/com.github.square.fderekey.XH5ErT
Nov  8 08:54:16 NAMEOFMACHINE installd[79389]: ./postinstall: 2017-11-08 08:54:16.197 sysadminctl[92964:11675276] Creating user record…
Nov  8 08:54:16 NAMEOFMACHINE installd[79389]: ./postinstall: 2017-11-08 08:54:16.217 sysadminctl[92964:11675276] ### Error:-14135 File:/Library/Caches/com.apple.xbs/Sources/Admin/Admin-633/DSRecord.m Line:501
Nov  8 08:54:16 NAMEOFMACHINE installd[79389]: ./postinstall: 2017-11-08 08:54:16.218 sysadminctl[92964:11675276] Assigning UID: 3
Nov  8 08:54:17 NAMEOFMACHINE installd[79389]: ./postinstall: 2017-11-08 08:54:17.277 sysadminctl[92964:11675276] Creating home directory at /Users/fderekey
Nov  8 08:54:17 NAMEOFMACHINE installd[79389]: ./postinstall: 2017-11-08 08:54:17.277 sysadminctl[92964:11675276] Directory at path:/Users/fderekey already exists
Nov  8 08:54:18 NAMEOFMACHINE installd[79389]: ./postinstall: 2017-11-08 08:54:18.799 sysadminctl[92981:11675513] Killing all processes for UID 3
Nov  8 08:54:18 NAMEOFMACHINE installd[79389]: ./postinstall: 2017-11-08 08:54:18.801 sysadminctl[92981:11675513] Securely removing fderekey's home at /Users/fderekey
Nov  8 08:54:18 NAMEOFMACHINE installd[79389]: ./postinstall: 2017-11-08 08:54:18.834 sysadminctl[92981:11675513] Deleting Public share point for fderekey
Nov  8 08:54:18 NAMEOFMACHINE installd[79389]: ./postinstall: 2017-11-08 08:54:18.843 sysadminctl[92981:11675513] Deleting record for fderekey
Nov  8 08:54:18 NAMEOFMACHINE installd[79389]: ./postinstall: Found User "fderekey" in user list.
Nov  8 08:54:18 NAMEOFMACHINE installd[79389]: ./postinstall: Tried 5 times to add user to FileVault and Failed each time...
Nov  8 08:54:18 NAMEOFMACHINE installd[79389]: ./postinstall: ERROR! Failed to add user "fderekey" to FileVault...
Nov  8 08:54:19 NAMEOFMACHINE installd[79389]: PackageKit: releasing backupd
Nov  8 08:54:19 NAMEOFMACHINE installd[79389]: PackageKit: allow user idle system sleep
Nov  8 08:54:19 NAMEOFMACHINE installd[79389]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “fde-rekey-1.0.2.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Library/Managed%20Installs/Cache/fde-rekey-1.0.2.pkg#fde-rekey.pkg, PKInstallPackageIdentifier=com.github.square.fderekey, NSLocalizedDescription=An error occurred while running scripts from the package “fde-rekey-1.0.2.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cfde-rekey-1.0.2.pkg\U201d.";
	    NSURL = "file://localhost/Library/Managed%20Installs/Cache/fde-rekey-1.0.2.pkg#fde-rekey.pkg";
	    PKInstallPackageIdentifier = "com.github.square.fderekey";
	}
Nov  8 08:54:19 NAMEOFMACHINE installer[92957]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “fde-rekey-1.0.2.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Library/Managed%20Installs/Cache/fde-rekey-1.0.2.pkg#fde-rekey.pkg, PKInstallPackageIdentifier=com.github.square.fderekey, NSLocalizedDescription=An error occurred while running scripts from the package “fde-rekey-1.0.2.pkg”.}
Nov  8 08:54:19 NAMEOFMACHINE installd[79389]: PackageKit: Running idle tasks
Nov  8 08:54:19 NAMEOFMACHINE installd[79389]: PackageKit: Removing client PKInstallDaemonClient pid=92957, uid=0 (/usr/sbin/installer)
Nov  8 08:54:19 NAMEOFMACHINE installd[79389]: PackageKit: Done with sandbox removals
Nov  8 08:54:20 NAMEOFMACHINE installer[92957]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
```
